# The book's title. Will be used everywhere!
title: "Kitabu"

# The book's language.
language: en

# Your book copyright info.
# Here's some examples:
#
#   Copyright 2016 by Matt Bettinson.
#   Copyright 2016 by Matt Bettinson. This work is licensed under MIT License.
#   This work is licensed under a Creative Commons Attribution-ShareAlike 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
#   This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License.
#
copyright: "Copyright (C) 2016 Matt Bettinson."

# Who's publishing this book.
publisher: "Matt Bettinson"

# When this book was published.
published_at: "2016-12-10"

# Some book description.
subject: "This guide will help you understand how all of the pieces fit together on Kitabu."

# Some keywords that identify this book.
keywords: "kitabu, e-book, kindlegen, epub, mobi, pdf, prince"

# Some unique identification. Works great with your domain
# like `http://yourbook.example.com`.
uid: "af31a5e47efa5ccef93d23969dce9840"

# Your book identification like ISBN or ISSN.
identifier:
  id: "http://yourbook.example.com"
  type: "URL" # can be ISBN, ISSN or URL

# This book authors.
authors:
  - "Matt Bettinson"

# Syntax highlight theme. Can be any of supported by Rouge.
theme: github
